import { Component, Input } from '@angular/core';
import { InputTextComponent } from '../input-text/input-text.component';
import { FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { InputSelectComponent } from '../input-select/input-select.component';
import { InputNumberComponent } from '../input-number/input-number.component';

@Component({
  selector: 'app-input-phone',
  templateUrl: './input-phone.component.html',
  styleUrl: './input-phone.component.scss',
  standalone: true,
  imports: [
    InputNumberComponent,
    InputTextComponent,
    InputSelectComponent,
    FormsModule,
    ReactiveFormsModule,
  ],
})
export class InputPhoneComponent {
  @Input() formGroup: FormGroup<any> = new FormGroup({});
  @Input() labelNumber: string = 'Phone number';
  @Input() labelPrefix: string = 'Prefix';
  @Input() placeholder: string = 'Insert your phone number';
  @Input() controlNameNumber: string = 'phone';
  @Input() controlNamePrefix: string = 'prefix';
  phoneNumbers = [
    {
      codeFlag: '🇺🇸 +1  ',
      text: '🇺🇸 +1   United States',
      code: '+1',
      country: 'US',
    },
    {
      codeFlag: '🇨🇦 +1  ',
      text: '🇨🇦 +1   Canada',
      code: '+1',
      country: 'CA',
    },
    {
      codeFlag: '🇷🇺 +7  ',
      text: '🇷🇺 +7   Russia',
      code: '+7',
      country: 'RU',
    },
    {
      codeFlag: '🇪🇬 +20 ',
      text: '🇪🇬 +20  Egypt',
      code: '+20',
      country: 'EG',
    },
    {
      codeFlag: '🇿🇦 +27 ',
      text: '🇿🇦 +27  South Africa',
      code: '+27',
      country: 'ZA',
    },
    {
      codeFlag: '🇬🇷 +30 ',
      text: '🇬🇷 +30  Greece',
      code: '+30',
      country: 'GR',
    },
    {
      codeFlag: '🇳🇱 +31 ',
      text: '🇳🇱 +31  Netherlands',
      code: '+31',
      country: 'NL',
    },
    {
      codeFlag: '🇧🇪 +32 ',
      text: '🇧🇪 +32  Belgium',
      code: '+32',
      country: 'BE',
    },
    {
      codeFlag: '🇫🇷 +33 ',
      text: '🇫🇷 +33  France',
      code: '+33',
      country: 'FR',
    },
    {
      codeFlag: '🇪🇸 +34 ',
      text: '🇪🇸 +34  Spain',
      code: '+34',
      country: 'ES',
    },
    {
      codeFlag: '🇭🇺 +36 ',
      text: '🇭🇺 +36  Hungary',
      code: '+36',
      country: 'HU',
    },
    {
      codeFlag: '🇮🇹 +39 ',
      text: '🇮🇹 +39  Italy',
      code: '+39',
      country: 'IT',
    },
    {
      codeFlag: '🇷🇴 +40 ',
      text: '🇷🇴 +40  Romania',
      code: '+40',
      country: 'RO',
    },
    {
      codeFlag: '🇨🇭 +41 ',
      text: '🇨🇭 +41  Switzerland',
      code: '+41',
      country: 'CH',
    },
    {
      codeFlag: '🇦🇹 +43 ',
      text: '🇦🇹 +43  Austria',
      code: '+43',
      country: 'AT',
    },
    {
      codeFlag: '🇬🇧 +44 ',
      text: '🇬🇧 +44  United Kingdom',
      code: '+44',
      country: 'GB',
    },
    {
      codeFlag: '🇩🇰 +45 ',
      text: '🇩🇰 +45  Denmark',
      code: '+45',
      country: 'DK',
    },
    {
      codeFlag: '🇸🇪 +46 ',
      text: '🇸🇪 +46  Sweden',
      code: '+46',
      country: 'SE',
    },
    {
      codeFlag: '🇳🇴 +47 ',
      text: '🇳🇴 +47  Norway',
      code: '+47',
      country: 'NO',
    },
    {
      codeFlag: '🇵🇱 +48 ',
      text: '🇵🇱 +48  Poland',
      code: '+48',
      country: 'PL',
    },
    {
      codeFlag: '🇩🇪 +49 ',
      text: '🇩🇪 +49  Germany',
      code: '+49',
      country: 'DE',
    },
    {
      codeFlag: '🇵🇪 +51 ',
      text: '🇵🇪 +51  Peru',
      code: '+51',
      country: 'PE',
    },
    {
      codeFlag: '🇲🇽 +52 ',
      text: '🇲🇽 +52  Mexico',
      code: '+52',
      country: 'MX',
    },
    {
      codeFlag: '🇨🇺 +53 ',
      text: '🇨🇺 +53  Cuba',
      code: '+53',
      country: 'CU',
    },
    {
      codeFlag: '🇦🇷 +54 ',
      text: '🇦🇷 +54  Argentina',
      code: '+54',
      country: 'AR',
    },
    {
      codeFlag: '🇧🇷 +55 ',
      text: '🇧🇷 +55  Brazil',
      code: '+55',
      country: 'BR',
    },
    {
      codeFlag: '🇨🇱 +56 ',
      text: '🇨🇱 +56  Chile',
      code: '+56',
      country: 'CL',
    },
    {
      codeFlag: '🇨🇴 +57 ',
      text: '🇨🇴 +57  Colombia',
      code: '+57',
      country: 'CO',
    },
    {
      codeFlag: '🇻🇪 +58 ',
      text: '🇻🇪 +58  Venezuela',
      code: '+58',
      country: 'VE',
    },
    {
      codeFlag: '🇲🇾 +60 ',
      text: '🇲🇾 +60  Malaysia',
      code: '+60',
      country: 'MY',
    },
    {
      codeFlag: '🇦🇺 +61 ',
      text: '🇦🇺 +61  Australia',
      code: '+61',
      country: 'AU',
    },
    {
      codeFlag: '🇮🇩 +62 ',
      text: '🇮🇩 +62  Indonesia',
      code: '+62',
      country: 'ID',
    },
    {
      codeFlag: '🇵🇭 +63 ',
      text: '🇵🇭 +63  Philippines',
      code: '+63',
      country: 'PH',
    },
    {
      codeFlag: '🇳🇿 +64 ',
      text: '🇳🇿 +64  New Zealand',
      code: '+64',
      country: 'NZ',
    },
    {
      codeFlag: '🇸🇬 +65 ',
      text: '🇸🇬 +65  Singapore',
      code: '+65',
      country: 'SG',
    },
    {
      codeFlag: '🇹🇭 +66 ',
      text: '🇹🇭 +66  Thailand',
      code: '+66',
      country: 'TH',
    },
    {
      codeFlag: '🇯🇵 +81 ',
      text: '🇯🇵 +81  Japan',
      code: '+81',
      country: 'JP',
    },
    {
      codeFlag: '🇰🇷 +82 ',
      text: '🇰🇷 +82  South Korea',
      code: '+82',
      country: 'KR',
    },
    {
      codeFlag: '🇻🇳 +84 ',
      text: '🇻🇳 +84  Vietnam',
      code: '+84',
      country: 'VN',
    },
    {
      codeFlag: '🇨🇳 +86 ',
      text: '🇨🇳 +86  China',
      code: '+86',
      country: 'CN',
    },
    {
      codeFlag: '🇹🇷 +90 ',
      text: '🇹🇷 +90  Turkey',
      code: '+90',
      country: 'TR',
    },
    {
      codeFlag: '🇮🇳 +91 ',
      text: '🇮🇳 +91  India',
      code: '+91',
      country: 'IN',
    },
    {
      codeFlag: '🇵🇰 +92 ',
      text: '🇵🇰 +92  Pakistan',
      code: '+92',
      country: 'PK',
    },
    {
      codeFlag: '🇦🇫 +93 ',
      text: '🇦🇫 +93  Afghanistan',
      code: '+93',
      country: 'AF',
    },
    {
      codeFlag: '🇱🇰 +94 ',
      text: '🇱🇰 +94  Sri Lanka',
      code: '+94',
      country: 'LK',
    },
    {
      codeFlag: '🇲🇲 +95 ',
      text: '🇲🇲 +95  Myanmar',
      code: '+95',
      country: 'MM',
    },
    {
      codeFlag: '🇮🇷 +98 ',
      text: '🇮🇷 +98  Iran',
      code: '+98',
      country: 'IR',
    },
    {
      codeFlag: '🇲🇦 +212',
      text: '🇲🇦 +212 Morocco',
      code: '+212',
      country: 'MA',
    },
    {
      codeFlag: '🇩🇿 +213',
      text: '🇩🇿 +213 Algeria',
      code: '+213',
      country: 'DZ',
    },
    {
      codeFlag: '🇹🇳 +216',
      text: '🇹🇳 +216 Tunisia',
      code: '+216',
      country: 'TN',
    },
    {
      codeFlag: '🇱🇾 +218',
      text: '🇱🇾 +218 Libya',
      code: '+218',
      country: 'LY',
    },
    {
      codeFlag: '🇬🇲 +220',
      text: '🇬🇲 +220 Gambia',
      code: '+220',
      country: 'GM',
    },
    {
      codeFlag: '🇸🇳 +221',
      text: '🇸🇳 +221 Senegal',
      code: '+221',
      country: 'SN',
    },
    {
      codeFlag: '🇲🇷 +222',
      text: '🇲🇷 +222 Mauritania',
      code: '+222',
      country: 'MR',
    },
    {
      codeFlag: '🇲🇱 +223',
      text: '🇲🇱 +223 Mali',
      code: '+223',
      country: 'ML',
    },
    {
      codeFlag: '🇬🇳 +224',
      text: '🇬🇳 +224 Guinea',
      code: '+224',
      country: 'GN',
    },
    {
      codeFlag: '🇨🇮 +225',
      text: '🇨🇮 +225 Ivory Coast',
      code: '+225',
      country: 'CI',
    },
    {
      codeFlag: '🇧🇫 +226',
      text: '🇧🇫 +226 Burkina Faso',
      code: '+226',
      country: 'BF',
    },
    {
      codeFlag: '🇳🇪 +227',
      text: '🇳🇪 +227 Niger',
      code: '+227',
      country: 'NE',
    },
    {
      codeFlag: '🇹🇬 +228',
      text: '🇹🇬 +228 Togo',
      code: '+228',
      country: 'TG',
    },
    {
      codeFlag: '🇧🇯 +229',
      text: '🇧🇯 +229 Benin',
      code: '+229',
      country: 'BJ',
    },
    {
      codeFlag: '🇲🇺 +230',
      text: '🇲🇺 +230 Mauritius',
      code: '+230',
      country: 'MU',
    },
    {
      codeFlag: '🇱🇷 +231',
      text: '🇱🇷 +231 Liberia',
      code: '+231',
      country: 'LR',
    },
    {
      codeFlag: '🇸🇱 +232',
      text: '🇸🇱 +232 Sierra Leone',
      code: '+232',
      country: 'SL',
    },
    {
      codeFlag: '🇬🇭 +233',
      text: '🇬🇭 +233 Ghana',
      code: '+233',
      country: 'GH',
    },
    {
      codeFlag: '🇳🇬 +234',
      text: '🇳🇬 +234 Nigeria',
      code: '+234',
      country: 'NG',
    },
    {
      codeFlag: '🇹🇩 +235',
      text: '🇹🇩 +235 Chad',
      code: '+235',
      country: 'TD',
    },
    {
      codeFlag: '🇨🇫 +236',
      text: '🇨🇫 +236 Central African Republic',
      code: '+236',
      country: 'CF',
    },
    {
      codeFlag: '🇨🇲 +237',
      text: '🇨🇲 +237 Cameroon',
      code: '+237',
      country: 'CM',
    },
    {
      codeFlag: '🇨🇻 +238',
      text: '🇨🇻 +238 Cape Verde',
      code: '+238',
      country: 'CV',
    },
    {
      codeFlag: '🇸🇹 +239',
      text: '🇸🇹 +239 Sao Tome and Principe',
      code: '+239',
      country: 'ST',
    },
    {
      codeFlag: '🇬🇶 +240',
      text: '🇬🇶 +240 Equatorial Guinea',
      code: '+240',
      country: 'GQ',
    },
    {
      codeFlag: '🇬🇦 +241',
      text: '🇬🇦 +241 Gabon',
      code: '+241',
      country: 'GA',
    },
    {
      codeFlag: '🇨🇬 +242',
      text: '🇨🇬 +242 Republic of the Congo',
      code: '+242',
      country: 'CG',
    },
    {
      codeFlag: '🇨🇩 +243',
      text: '🇨🇩 +243 Democratic Republic of the Congo',
      code: '+243',
      country: 'CD',
    },
    {
      codeFlag: '🇦🇴 +244',
      text: '🇦🇴 +244 Angola',
      code: '+244',
      country: 'AO',
    },
    {
      codeFlag: '🇬🇼 +245',
      text: '🇬🇼 +245 Guinea-Bissau',
      code: '+245',
      country: 'GW',
    },
    {
      codeFlag: '🇮🇴 +246',
      text: '🇮🇴 +246 British Indian Ocean Territory',
      code: '+246',
      country: 'IO',
    },
    {
      codeFlag: '🇸🇨 +248',
      text: '🇸🇨 +248 Seychelles',
      code: '+248',
      country: 'SC',
    },
    {
      codeFlag: '🇸🇩 +249',
      text: '🇸🇩 +249 Sudan',
      code: '+249',
      country: 'SD',
    },
    {
      codeFlag: '🇷🇼 +250',
      text: '🇷🇼 +250 Rwanda',
      code: '+250',
      country: 'RW',
    },
    {
      codeFlag: '🇪🇹 +251',
      text: '🇪🇹 +251 Ethiopia',
      code: '+251',
      country: 'ET',
    },
    {
      codeFlag: '🇸🇴 +252',
      text: '🇸🇴 +252 Somalia',
      code: '+252',
      country: 'SO',
    },
    {
      codeFlag: '🇩🇯 +253',
      text: '🇩🇯 +253 Djibouti',
      code: '+253',
      country: 'DJ',
    },
    {
      codeFlag: '🇰🇪 +254',
      text: '🇰🇪 +254 Kenya',
      code: '+254',
      country: 'KE',
    },
    {
      codeFlag: '🇹🇿 +255',
      text: '🇹🇿 +255 Tanzania',
      code: '+255',
      country: 'TZ',
    },
    {
      codeFlag: '🇺🇬 +256',
      text: '🇺🇬 +256 Uganda',
      code: '+256',
      country: 'UG',
    },
    {
      codeFlag: '🇧🇮 +257',
      text: '🇧🇮 +257 Burundi',
      code: '+257',
      country: 'BI',
    },
    {
      codeFlag: '🇲🇿 +258',
      text: '🇲🇿 +258 Mozambique',
      code: '+258',
      country: 'MZ',
    },
    {
      codeFlag: '🇿🇲 +260',
      text: '🇿🇲 +260 Zambia',
      code: '+260',
      country: 'ZM',
    },
    {
      codeFlag: '🇲🇬 +261',
      text: '🇲🇬 +261 Madagascar',
      code: '+261',
      country: 'MG',
    },
    {
      codeFlag: '🇷🇪 +262',
      text: '🇷🇪 +262 Reunion',
      code: '+262',
      country: 'RE',
    },
    {
      codeFlag: '🇿🇼 +263',
      text: '🇿🇼 +263 Zimbabwe',
      code: '+263',
      country: 'ZW',
    },
    {
      codeFlag: '🇳🇦 +264',
      text: '🇳🇦 +264 Namibia',
      code: '+264',
      country: 'NA',
    },
    {
      codeFlag: '🇲🇼 +265',
      text: '🇲🇼 +265 Malawi',
      code: '+265',
      country: 'MW',
    },
    {
      codeFlag: '🇱🇸 +266',
      text: '🇱🇸 +266 Lesotho',
      code: '+266',
      country: 'LS',
    },
    {
      codeFlag: '🇧🇼 +267',
      text: '🇧🇼 +267 Botswana',
      code: '+267',
      country: 'BW',
    },
    {
      codeFlag: '🇸🇿 +268',
      text: '🇸🇿 +268 Eswatini',
      code: '+268',
      country: 'SZ',
    },
    {
      codeFlag: '🇰🇲 +269',
      text: '🇰🇲 +269 Comoros',
      code: '+269',
      country: 'KM',
    },
    {
      codeFlag: '🇸🇭 +290',
      text: '🇸🇭 +290 Saint Helena',
      code: '+290',
      country: 'SH',
    },
    {
      codeFlag: '🇪🇷 +291',
      text: '🇪🇷 +291 Eritrea',
      code: '+291',
      country: 'ER',
    },
    {
      codeFlag: '🇦🇼 +297',
      text: '🇦🇼 +297 Aruba',
      code: '+297',
      country: 'AW',
    },
    {
      codeFlag: '🇫🇴 +298',
      text: '🇫🇴 +298 Faroe Islands',
      code: '+298',
      country: 'FO',
    },
    {
      codeFlag: '🇬🇱 +299',
      text: '🇬🇱 +299 Greenland',
      code: '+299',
      country: 'GL',
    },
    {
      codeFlag: '🇬🇮 +350',
      text: '🇬🇮 +350 Gibraltar',
      code: '+350',
      country: 'GI',
    },
    {
      codeFlag: '🇵🇹 +351',
      text: '🇵🇹 +351 Portugal',
      code: '+351',
      country: 'PT',
    },
    {
      codeFlag: '🇱🇺 +352',
      text: '🇱🇺 +352 Luxembourg',
      code: '+352',
      country: 'LU',
    },
    {
      codeFlag: '🇮🇪 +353',
      text: '🇮🇪 +353 Ireland',
      code: '+353',
      country: 'IE',
    },
    {
      codeFlag: '🇮🇸 +354',
      text: '🇮🇸 +354 Iceland',
      code: '+354',
      country: 'IS',
    },
    {
      codeFlag: '🇦🇱 +355',
      text: '🇦🇱 +355 Albania',
      code: '+355',
      country: 'AL',
    },
    {
      codeFlag: '🇲🇹 +356',
      text: '🇲🇹 +356 Malta',
      code: '+356',
      country: 'MT',
    },
    {
      codeFlag: '🇨🇾 +357',
      text: '🇨🇾 +357 Cyprus',
      code: '+357',
      country: 'CY',
    },
    {
      codeFlag: '🇫🇮 +358',
      text: '🇫🇮 +358 Finland',
      code: '+358',
      country: 'FI',
    },
    {
      codeFlag: '🇧🇬 +359',
      text: '🇧🇬 +359 Bulgaria',
      code: '+359',
      country: 'BG',
    },
    {
      codeFlag: '🇱🇹 +370',
      text: '🇱🇹 +370 Lithuania',
      code: '+370',
      country: 'LT',
    },
    {
      codeFlag: '🇱🇻 +371',
      text: '🇱🇻 +371 Latvia',
      code: '+371',
      country: 'LV',
    },
    {
      codeFlag: '🇪🇪 +372',
      text: '🇪🇪 +372 Estonia',
      code: '+372',
      country: 'EE',
    },
    {
      codeFlag: '🇲🇩 +373',
      text: '🇲🇩 +373 Moldova',
      code: '+373',
      country: 'MD',
    },
    {
      codeFlag: '🇦🇲 +374',
      text: '🇦🇲 +374 Armenia',
      code: '+374',
      country: 'AM',
    },
    {
      codeFlag: '🇧🇾 +375',
      text: '🇧🇾 +375 Belarus',
      code: '+375',
      country: 'BY',
    },
    {
      codeFlag: '🇦🇩 +376',
      text: '🇦🇩 +376 Andorra',
      code: '+376',
      country: 'AD',
    },
    {
      codeFlag: '🇲🇨 +377',
      text: '🇲🇨 +377 Monaco',
      code: '+377',
      country: 'MC',
    },
    {
      codeFlag: '🇸🇲 +378',
      text: '🇸🇲 +378 San Marino',
      code: '+378',
      country: 'SM',
    },
    {
      codeFlag: '🇺🇦 +380',
      text: '🇺🇦 +380 Ukraine',
      code: '+380',
      country: 'UA',
    },
    {
      codeFlag: '🇷🇸 +381',
      text: '🇷🇸 +381 Serbia',
      code: '+381',
      country: 'RS',
    },
    {
      codeFlag: '🇲🇪 +382',
      text: '🇲🇪 +382 Montenegro',
      code: '+382',
      country: 'ME',
    },
    {
      codeFlag: '🇭🇷 +385',
      text: '🇭🇷 +385 Croatia',
      code: '+385',
      country: 'HR',
    },
    {
      codeFlag: '🇸🇮 +386',
      text: '🇸🇮 +386 Slovenia',
      code: '+386',
      country: 'SI',
    },
    {
      codeFlag: '🇧🇦 +387',
      text: '🇧🇦 +387 Bosnia and Herzegovina',
      code: '+387',
      country: 'BA',
    },
    {
      codeFlag: '🇲🇰 +389',
      text: '🇲🇰 +389 North Macedonia',
      code: '+389',
      country: 'MK',
    },
    {
      codeFlag: '🇨🇿 +420',
      text: '🇨🇿 +420 Czech Republic',
      code: '+420',
      country: 'CZ',
    },
    {
      codeFlag: '🇸🇰 +421',
      text: '🇸🇰 +421 Slovakia',
      code: '+421',
      country: 'SK',
    },
    {
      codeFlag: '🇱🇮 +423',
      text: '🇱🇮 +423 Liechtenstein',
      code: '+423',
      country: 'LI',
    },
    {
      codeFlag: '🇫🇰 +500',
      text: '🇫🇰 +500 Falkland Islands',
      code: '+500',
      country: 'FK',
    },
    {
      codeFlag: '🇧🇿 +501',
      text: '🇧🇿 +501 Belize',
      code: '+501',
      country: 'BZ',
    },
    {
      codeFlag: '🇬🇹 +502',
      text: '🇬🇹 +502 Guatemala',
      code: '+502',
      country: 'GT',
    },
    {
      codeFlag: '🇸🇻 +503',
      text: '🇸🇻 +503 El Salvador',
      code: '+503',
      country: 'SV',
    },
    {
      codeFlag: '🇭🇳 +504',
      text: '🇭🇳 +504 Honduras',
      code: '+504',
      country: 'HN',
    },
    {
      codeFlag: '🇳🇮 +505',
      text: '🇳🇮 +505 Nicaragua',
      code: '+505',
      country: 'NI',
    },
    {
      codeFlag: '🇨🇷 +506',
      text: '🇨🇷 +506 Costa Rica',
      code: '+506',
      country: 'CR',
    },
    {
      codeFlag: '🇵🇦 +507',
      text: '🇵🇦 +507 Panama',
      code: '+507',
      country: 'PA',
    },
    {
      codeFlag: '🇵🇲 +508',
      text: '🇵🇲 +508 Saint Pierre and Miquelon',
      code: '+508',
      country: 'PM',
    },
    {
      codeFlag: '🇭🇹 +509',
      text: '🇭🇹 +509 Haiti',
      code: '+509',
      country: 'HT',
    },
    {
      codeFlag: '🇬🇵 +590',
      text: '🇬🇵 +590 Guadeloupe',
      code: '+590',
      country: 'GP',
    },
    {
      codeFlag: '🇧🇴 +591',
      text: '🇧🇴 +591 Bolivia',
      code: '+591',
      country: 'BO',
    },
    {
      codeFlag: '🇬🇾 +592',
      text: '🇬🇾 +592 Guyana',
      code: '+592',
      country: 'GY',
    },
    {
      codeFlag: '🇪🇨 +593',
      text: '🇪🇨 +593 Ecuador',
      code: '+593',
      country: 'EC',
    },
    {
      codeFlag: '🇬🇫 +594',
      text: '🇬🇫 +594 French Guiana',
      code: '+594',
      country: 'GF',
    },
    {
      codeFlag: '🇵🇾 +595',
      text: '🇵🇾 +595 Paraguay',
      code: '+595',
      country: 'PY',
    },
    {
      codeFlag: '🇲🇶 +596',
      text: '🇲🇶 +596 Martinique',
      code: '+596',
      country: 'MQ',
    },
    {
      codeFlag: '🇸🇷 +597',
      text: '🇸🇷 +597 Suriname',
      code: '+597',
      country: 'SR',
    },
    {
      codeFlag: '🇺🇾 +598',
      text: '🇺🇾 +598 Uruguay',
      code: '+598',
      country: 'UY',
    },
    {
      codeFlag: '🇨🇼 +599',
      text: '🇨🇼 +599 Curaçao',
      code: '+599',
      country: 'CW',
    },
    {
      codeFlag: '🇹🇱 +670',
      text: '🇹🇱 +670 Timor-Leste',
      code: '+670',
      country: 'TL',
    },
    {
      codeFlag: '🇦🇶 +672',
      text: '🇦🇶 +672 Antarctica',
      code: '+672',
      country: 'AQ',
    },
    {
      codeFlag: '🇧🇳 +673',
      text: '🇧🇳 +673 Brunei',
      code: '+673',
      country: 'BN',
    },
    {
      codeFlag: '🇳🇷 +674',
      text: '🇳🇷 +674 Nauru',
      code: '+674',
      country: 'NR',
    },
    {
      codeFlag: '🇵🇬 +675',
      text: '🇵🇬 +675 Papua New Guinea',
      code: '+675',
      country: 'PG',
    },
    {
      codeFlag: '🇹🇴 +676',
      text: '🇹🇴 +676 Tonga',
      code: '+676',
      country: 'TO',
    },
    {
      codeFlag: '🇸🇧 +677',
      text: '🇸🇧 +677 Solomon Islands',
      code: '+677',
      country: 'SB',
    },
    {
      codeFlag: '🇻🇺 +678',
      text: '🇻🇺 +678 Vanuatu',
      code: '+678',
      country: 'VU',
    },
    {
      codeFlag: '🇫🇯 +679',
      text: '🇫🇯 +679 Fiji',
      code: '+679',
      country: 'FJ',
    },
    {
      codeFlag: '🇵🇼 +680',
      text: '🇵🇼 +680 Palau',
      code: '+680',
      country: 'PW',
    },
    {
      codeFlag: '🇼🇫 +681',
      text: '🇼🇫 +681 Wallis and Futuna',
      code: '+681',
      country: 'WF',
    },
    {
      codeFlag: '🇨🇰 +682',
      text: '🇨🇰 +682 Cook Islands',
      code: '+682',
      country: 'CK',
    },
    {
      codeFlag: '🇳🇺 +683',
      text: '🇳🇺 +683 Niue',
      code: '+683',
      country: 'NU',
    },
    {
      codeFlag: '🇼🇸 +685',
      text: '🇼🇸 +685 Samoa',
      code: '+685',
      country: 'WS',
    },
    {
      codeFlag: '🇰🇮 +686',
      text: '🇰🇮 +686 Kiribati',
      code: '+686',
      country: 'KI',
    },
    {
      codeFlag: '🇳🇨 +687',
      text: '🇳🇨 +687 New Caledonia',
      code: '+687',
      country: 'NC',
    },
    {
      codeFlag: '🇹🇻 +688',
      text: '🇹🇻 +688 Tuvalu',
      code: '+688',
      country: 'TV',
    },
    {
      codeFlag: '🇵🇫 +689',
      text: '🇵🇫 +689 French Polynesia',
      code: '+689',
      country: 'PF',
    },
    {
      codeFlag: '🇹🇰 +690',
      text: '🇹🇰 +690 Tokelau',
      code: '+690',
      country: 'TK',
    },
    {
      codeFlag: '🇫🇲 +691',
      text: '🇫🇲 +691 Federated States of Micronesia',
      code: '+691',
      country: 'FM',
    },
    {
      codeFlag: '🇲🇭 +692',
      text: '🇲🇭 +692 Marshall Islands',
      code: '+692',
      country: 'MH',
    },
    {
      codeFlag: '🇰🇵 +850',
      text: '🇰🇵 +850 North Korea',
      code: '+850',
      country: 'KP',
    },
    {
      codeFlag: '🇭🇰 +852',
      text: '🇭🇰 +852 Hong Kong',
      code: '+852',
      country: 'HK',
    },
    {
      codeFlag: '🇲🇴 +853',
      text: '🇲🇴 +853 Macau',
      code: '+853',
      country: 'MO',
    },
    {
      codeFlag: '🇰🇭 +855',
      text: '🇰🇭 +855 Cambodia',
      code: '+855',
      country: 'KH',
    },
    {
      codeFlag: '🇱🇦 +856',
      text: '🇱🇦 +856 Laos',
      code: '+856',
      country: 'LA',
    },
    {
      codeFlag: '🇧🇩 +880',
      text: '🇧🇩 +880 Bangladesh',
      code: '+880',
      country: 'BD',
    },
    {
      codeFlag: '🇹🇼 +886',
      text: '🇹🇼 +886 Taiwan',
      code: '+886',
      country: 'TW',
    },
    {
      codeFlag: '🇲🇻 +960',
      text: '🇲🇻 +960 Maldives',
      code: '+960',
      country: 'MV',
    },
    {
      codeFlag: '🇱🇧 +961',
      text: '🇱🇧 +961 Lebanon',
      code: '+961',
      country: 'LB',
    },
    {
      codeFlag: '🇯🇴 +962',
      text: '🇯🇴 +962 Jordan',
      code: '+962',
      country: 'JO',
    },
    {
      codeFlag: '🇸🇾 +963',
      text: '🇸🇾 +963 Syria',
      code: '+963',
      country: 'SY',
    },
    {
      codeFlag: '🇮🇶 +964',
      text: '🇮🇶 +964 Iraq',
      code: '+964',
      country: 'IQ',
    },
    {
      codeFlag: '🇰🇼 +965',
      text: '🇰🇼 +965 Kuwait',
      code: '+965',
      country: 'KW',
    },
    {
      codeFlag: '🇸🇦 +966',
      text: '🇸🇦 +966 Saudi Arabia',
      code: '+966',
      country: 'SA',
    },
    {
      codeFlag: '🇾🇪 +967',
      text: '🇾🇪 +967 Yemen',
      code: '+967',
      country: 'YE',
    },
    {
      codeFlag: '🇴🇲 +968',
      text: '🇴🇲 +968 Oman',
      code: '+968',
      country: 'OM',
    },
    {
      codeFlag: '🇵🇸 +970',
      text: '🇵🇸 +970 Palestine',
      code: '+970',
      country: 'PS',
    },
    {
      codeFlag: '🇦🇪 +971',
      text: '🇦🇪 +971 United Arab Emirates',
      code: '+971',
      country: 'AE',
    },
    {
      codeFlag: '🇮🇱 +972',
      text: '🇮🇱 +972 Israel',
      code: '+972',
      country: 'IL',
    },
    {
      codeFlag: '🇧🇭 +973',
      text: '🇧🇭 +973 Bahrain',
      code: '+973',
      country: 'BH',
    },
    {
      codeFlag: '🇶🇦 +974',
      text: '🇶🇦 +974 Qatar',
      code: '+974',
      country: 'QA',
    },
    {
      codeFlag: '🇧🇹 +975',
      text: '🇧🇹 +975 Bhutan',
      code: '+975',
      country: 'BT',
    },
    {
      codeFlag: '🇲🇳 +976',
      text: '🇲🇳 +976 Mongolia',
      code: '+976',
      country: 'MN',
    },
    {
      codeFlag: '🇳🇵 +977',
      text: '🇳🇵 +977 Nepal',
      code: '+977',
      country: 'NP',
    },
    {
      codeFlag: '🇹🇯 +992',
      text: '🇹🇯 +992 Tajikistan',
      code: '+992',
      country: 'TJ',
    },
    {
      codeFlag: '🇹🇲 +993',
      text: '🇹🇲 +993 Turkmenistan',
      code: '+993',
      country: 'TM',
    },
    {
      codeFlag: '🇦🇿 +994',
      text: '🇦🇿 +994 Azerbaijan',
      code: '+994',
      country: 'AZ',
    },
    {
      codeFlag: '🇬🇪 +995',
      text: '🇬🇪 +995 Georgia',
      code: '+995',
      country: 'GE',
    },
    {
      codeFlag: '🇰🇬 +996',
      text: '🇰🇬 +996 Kyrgyzstan',
      code: '+996',
      country: 'KG',
    },
    {
      codeFlag: '🇺🇿 +998',
      text: '🇺🇿 +998 Uzbekistan',
      code: '+998',
      country: 'UZ',
    },
  ];

  selectedPhoneNumber: any = this.phoneNumbers[11].code;
  inputValue: string = '';
}
